# Generated by Django 4.1 on 2022-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_admin_user_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
