# Generated by Django 4.1 on 2022-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
