# Generated by Django 4.1 on 2022-08-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_freelancer',
        ),
    ]
