# Generated by Django 4.1 on 2022-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_birth_date_alter_user_is_freelancer'),
        ('accounts', '0008_user_is_freelancer'),
    ]

    operations = [
    ]
