# Generated by Django 4.1 on 2022-08-11 18:14

import apps.courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enroll',
            managers=[
                ('objects', apps.courses.models.EnrollManager()),
            ],
        ),
    ]
