# Generated by Django 4.1 on 2022-09-12 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 5, 42, 25, 452075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 5, 42, 25, 453675, tzinfo=datetime.timezone.utc)),
        ),
    ]
