# Generated by Django 4.1 on 2022-08-13 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_created_at_alter_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now().astimezone(
    datetime.timezone(datetime.timedelta(hours=5, minutes=30)))),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now().astimezone(
    datetime.timezone(datetime.timedelta(hours=5, minutes=30)))),
        ),
    ]
