# Generated by Django 4.1 on 2022-08-13 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_created_at_alter_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 17, 0, 24, 277054)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 17, 0, 24, 278561)),
        ),
    ]
