# Generated by Django 4.1 on 2022-08-11 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_enroll_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enroll')),
            ],
        ),
    ]
